apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-springboot
  template:
    metadata:
      labels:
        app: tomcat-springboot
    spec:
      containers:
        - name: springboot
          image: marif2/dockeransiblejenkins:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tomcat-springboot
